apiVersion: v1
kind: Namespace
metadata:
  name: inventario-dev
  labels:
    app.kubernetes.io/name: inventario-dev
    app.kubernetes.io/part-of: inventario
    app.kubernetes.io/managed-by: raw-yaml
    inventario.io/environment: dev