# GoReleaser configuration for Inventario
version: 1

before:
  hooks:
    # Build frontend assets first
    - make build-frontend

builds:
  - id: inventario
    main: .
    binary: inventario
    dir: go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    # Use build tags to include frontend assets
    flags:
      - -tags=with_frontend
    ldflags:
      - -s -w
      - -X github.com/denisvmedia/inventario/internal/version.Version={{.Version}}
      - -X github.com/denisvmedia/inventario/internal/version.Commit={{.Commit}}
      - -X github.com/denisvmedia/inventario/internal/version.Date={{.Date}}
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: inventario
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^build:'
      - Merge pull request
      - Merge branch
      - go mod tidy

release:
  github:
    owner: denisvmedia
    name: inventario
  prerelease: auto
  name_template: "Inventario v{{ .Version }}"
  header: |
    ## Inventario v{{ .Version }}
    
    This release includes the following changes:
  footer: |
    
    ## Installation
    
    ### Using pre-built binaries
    
    Download the appropriate binary for your platform from the assets below.
    
    ### Using Go
    
    ```bash
    go install github.com/denisvmedia/inventario@v{{ .Version }}
    ```