package seeddata

import (
	"context"
	"embed"
	"fmt"
	"path/filepath"

	"github.com/google/uuid"
	"gocloud.dev/blob"

	"github.com/denisvmedia/inventario/internal/blobkeys"
)

// fixturesFS bundles a handful of small JPG photos and PDF documents.
// The seed uploads these into the blob backend (when one is configured)
// and creates matching FileEntity rows so every commodity surface looks
// lived-in: real cover photos on the items list, real receipts on the
// Files page, real manuals on a few commodities.
//
// The six photo-*.jpg files are Pexels photos under the Pexels License
// (commercial use, no attribution required) — see
// _files/SOURCES.md for the per-file Pexels IDs and refresh recipe.
// The two PDFs are hand-rolled minimal documents generated by
// _files/gen_fixtures.go; they carry no licensing baggage.
//
// The full bundle is intentionally small (~130 KB) so go:embed stays
// cheap to ship in the binary.
//
//go:embed _files/photo-*.jpg _files/invoice.pdf _files/manual.pdf
var fixturesFS embed.FS

// fixtureKind names the bundled fixture variants the seed can ask for.
// Using a typed enum so callers in seeddata_inventory.go can't typo a
// fixture name without the compiler catching it.
type fixtureKind string

const (
	fixturePhotoLivingRoom fixtureKind = "_files/photo-livingroom.jpg"
	fixturePhotoKitchen    fixtureKind = "_files/photo-kitchen.jpg"
	fixturePhotoWork       fixtureKind = "_files/photo-work.jpg"
	fixturePhotoOutdoor    fixtureKind = "_files/photo-outdoor.jpg"
	fixturePhotoBedroom    fixtureKind = "_files/photo-bedroom.jpg"
	fixturePhotoStorage    fixtureKind = "_files/photo-storage.jpg"
	fixtureInvoice         fixtureKind = "_files/invoice.pdf"
	fixtureManual          fixtureKind = "_files/manual.pdf"
)

// fixtureMeta is the MIME / extension info paired with each fixture.
// File registry rows need Ext + MIMEType set, and downstream code
// dispatches off MIMEType (image vs document) so they have to match the
// actual bytes.
type fixtureMeta struct {
	Ext      string
	MIMEType string
}

var fixtureMetadata = map[fixtureKind]fixtureMeta{
	fixturePhotoLivingRoom: {Ext: ".jpg", MIMEType: "image/jpeg"},
	fixturePhotoKitchen:    {Ext: ".jpg", MIMEType: "image/jpeg"},
	fixturePhotoWork:       {Ext: ".jpg", MIMEType: "image/jpeg"},
	fixturePhotoOutdoor:    {Ext: ".jpg", MIMEType: "image/jpeg"},
	fixturePhotoBedroom:    {Ext: ".jpg", MIMEType: "image/jpeg"},
	fixturePhotoStorage:    {Ext: ".jpg", MIMEType: "image/jpeg"},
	fixtureInvoice:         {Ext: ".pdf", MIMEType: "application/pdf"},
	fixtureManual:          {Ext: ".pdf", MIMEType: "application/pdf"},
}

// blobUploader writes seed fixture bytes into the configured upload
// bucket. Implementations differ between "real backend" (open the bucket
// via gocloud, copy bytes through) and "no backend" (no-op — the seed
// still creates FileEntity rows so the UI surfaces the entry, but the
// row's OriginalPath points at a blob that won't exist if anyone tries
// to read it). The no-op path is what the in-memory unit tests use.
//
// Implementations construct tenant-prefixed blob keys via
// blobkeys.BuildSeedKey so seeded rows respect the same per-tenant
// namespace as user-uploaded files (#1793).
type blobUploader interface {
	upload(ctx context.Context, fixture fixtureKind, tenantID string) (storagePath string, sizeBytes int64, err error)
	close()
}

// newBlobUploader returns either a real or no-op uploader depending on
// whether an upload location was supplied to SeedData. An empty
// uploadLocation yields the no-op uploader (in-memory unit tests). A
// non-empty location that fails to open is surfaced as an error so the
// caller can fix the bucket and re-run — the seed deliberately does
// not silently fall back to the no-op path in production, because a
// silently-broken bucket would create FileEntity rows with paths that
// nothing can download.
func newBlobUploader(ctx context.Context, uploadLocation string) (blobUploader, error) {
	if uploadLocation == "" {
		return &noopUploader{}, nil
	}
	bucket, err := blob.OpenBucket(ctx, uploadLocation)
	if err != nil {
		return nil, fmt.Errorf("failed to open seed upload bucket %q: %w", uploadLocation, err)
	}
	return &bucketUploader{bucket: bucket}, nil
}

type noopUploader struct{}

func (*noopUploader) upload(_ context.Context, fixture fixtureKind, tenantID string) (string, int64, error) {
	// Even with no backend, give the row a plausible-looking path so
	// list endpoints don't trip on validation: the file rows must
	// carry a non-empty OriginalPath. The "seed-" prefix + UUID makes
	// these rows obvious if anyone debugs the table. The full key is
	// tenant-prefixed (#1793) for consistency with real uploads, even
	// though no bucket actually receives the bytes.
	basename := fmt.Sprintf("seed-%s%s", uuid.NewString(), filepath.Ext(string(fixture)))
	return blobkeys.BuildSeedKey(tenantID, basename), 0, nil
}

func (*noopUploader) close() {}

type bucketUploader struct {
	bucket *blob.Bucket
}

func (u *bucketUploader) upload(ctx context.Context, fixture fixtureKind, tenantID string) (string, int64, error) {
	data, err := fixturesFS.ReadFile(string(fixture))
	if err != nil {
		return "", 0, fmt.Errorf("failed to read fixture %s: %w", fixture, err)
	}
	basename := fmt.Sprintf("seed-%s%s", uuid.NewString(), filepath.Ext(string(fixture)))
	storagePath := blobkeys.BuildSeedKey(tenantID, basename)
	w, err := u.bucket.NewWriter(ctx, storagePath, nil)
	if err != nil {
		return "", 0, fmt.Errorf("failed to open bucket writer for %s: %w", storagePath, err)
	}
	if _, werr := w.Write(data); werr != nil {
		_ = w.Close()
		return "", 0, fmt.Errorf("failed to write seed fixture %s: %w", storagePath, werr)
	}
	if cerr := w.Close(); cerr != nil {
		return "", 0, fmt.Errorf("failed to close writer for %s: %w", storagePath, cerr)
	}
	return storagePath, int64(len(data)), nil
}

func (u *bucketUploader) close() {
	if u.bucket != nil {
		_ = u.bucket.Close()
	}
}

// fixtureExt returns the file extension stored in fixtureMetadata.
// Tiny convenience — keeps the inventory tables terse.
func fixtureExt(f fixtureKind) string {
	if meta, ok := fixtureMetadata[f]; ok {
		return meta.Ext
	}
	return filepath.Ext(string(f))
}

// fixtureMIME returns the MIME type stored in fixtureMetadata.
func fixtureMIME(f fixtureKind) string {
	if meta, ok := fixtureMetadata[f]; ok {
		return meta.MIMEType
	}
	return "application/octet-stream"
}

// ensureFixturesPresent is a sanity check the orchestrator can call
// before any blob work — verifies the embed bundle actually contains
// the expected files, surfacing a clear error if the package was built
// from an incomplete source tree.
func ensureFixturesPresent() error {
	for fx := range fixtureMetadata {
		if _, err := fixturesFS.ReadFile(string(fx)); err != nil {
			return fmt.Errorf("seed fixture %s missing from embed bundle: %w", fx, err)
		}
	}
	return nil
}
