apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: inventario-dev
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: data-service
    app.kubernetes.io/part-of: inventario
    app.kubernetes.io/managed-by: raw-yaml
    inventario.io/environment: dev
stringData:
  POSTGRES_DB: inventario
  POSTGRES_USER: inventario
  POSTGRES_PASSWORD: inventario_password
  POSTGRES_MIGRATOR_USER: inventario_migrator
  POSTGRES_MIGRATOR_PASSWORD: inventario_migrator_password
