apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: inventario-dev
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: data-service
    app.kubernetes.io/part-of: inventario
    app.kubernetes.io/managed-by: raw-yaml
    inventario.io/environment: dev
spec:
  selector:
    app.kubernetes.io/name: postgres
    inventario.io/environment: dev
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres