name: "Vars"
description: "Exposes versions for common tools used in workflows"
outputs:
  node_version:
    description: "Node.js version"
    value: ${{ steps.node.outputs.NODE_VERSION }}
runs:
  using: "composite"
  steps:
    - name: Read Node.js version from package.json
      id: node
      run: |
        echo "NODE_VERSION=$(jq -r .volta.node package.json)" >> $GITHUB_OUTPUT
      working-directory: frontend
      shell: bash
