#!/usr/bin/env node
// Convert go/docs/swagger.json (Swagger 2.0) → OpenAPI 3.0 → src/types/api.d.ts.
//
// `--check` mode regenerates into a temp file and exits non-zero if it differs
// from the committed file, used by the codegen-drift CI job.
import { mkdir, readFile, rm, writeFile } from "node:fs/promises"
import { existsSync } from "node:fs"
import { tmpdir } from "node:os"
import path from "node:path"
import { fileURLToPath } from "node:url"

import openapiTS, { astToString } from "openapi-typescript"
import { convertObj } from "swagger2openapi"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const repoRoot = path.resolve(__dirname, "..", "..")
const swaggerPath = path.join(repoRoot, "go", "docs", "swagger.json")
const outPath = path.join(__dirname, "..", "src", "types", "api.d.ts")
const checkMode = process.argv.includes("--check")

const banner =
  "// AUTO-GENERATED by `npm run codegen` from go/docs/swagger.json. DO NOT EDIT.\n" +
  "// To regenerate: run `npm run codegen` (or `make codegen-frontend`).\n\n"

async function generate() {
  if (!existsSync(swaggerPath)) {
    throw new Error(`swagger.json not found at ${swaggerPath} — run \`go tool swag init --output docs\` in /go first`)
  }
  const swagger2 = JSON.parse(await readFile(swaggerPath, "utf8"))
  const { openapi } = await convertObj(swagger2, { patch: true, warnOnly: true })
  const ast = await openapiTS(openapi, { exportType: true })
  return banner + astToString(ast)
}

async function run() {
  const generated = await generate()
  if (checkMode) {
    const current = existsSync(outPath) ? await readFile(outPath, "utf8") : ""
    if (current !== generated) {
      const tmpFile = path.join(tmpdir(), `inventario-api-${Date.now()}.d.ts`)
      await writeFile(tmpFile, generated, "utf8")
      console.error(
        "✗ src/types/api.d.ts is out of date.\n" +
          `  Run \`npm run codegen\` and commit the result.\n` +
          `  (regenerated copy: ${tmpFile})`,
      )
      process.exit(1)
    }
    console.log("✓ src/types/api.d.ts is up to date.")
    return
  }
  await mkdir(path.dirname(outPath), { recursive: true })
  await writeFile(outPath, generated, "utf8")
  console.log(`✓ wrote ${path.relative(process.cwd(), outPath)}`)
}

run().catch(async (err) => {
  console.error(err.stack ?? err.message ?? err)
  // Best-effort cleanup of any tmp dir we may have created (no-op for now).
  await rm(path.join(tmpdir(), "inventario-codegen"), { recursive: true, force: true }).catch(() => {})
  process.exit(1)
})
