apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: inventario-dev
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: data-service
    app.kubernetes.io/part-of: inventario
    app.kubernetes.io/managed-by: raw-yaml
    inventario.io/environment: dev
stringData:
  MINIO_ROOT_USER: inventario
  MINIO_ROOT_PASSWORD: inventario_minio_password
  MINIO_BUCKET_NAME: inventario
