apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: inventario-dev
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: data-service
    app.kubernetes.io/part-of: inventario
    app.kubernetes.io/managed-by: raw-yaml
    inventario.io/environment: dev
spec:
  selector:
    app.kubernetes.io/name: minio
    inventario.io/environment: dev
  ports:
    - name: api
      port: 9000
      targetPort: api
    - name: console
      port: 9001
      targetPort: console
