// Settings API client. The endpoint returns the full SettingsObject as
// generated by Swag from go/models/settings.go — camelCase field names,
// every entry optional (missing = use BE default). Patch is a thin
// shim over PATCH /settings/{field}; the BE accepts either a raw value
// or `{value: ...}` envelope and we pick the raw form here since the
// FE only ever sends primitives (boolean / string).
import { http } from "@/lib/http"
import type { Schema } from "@/types"

export type SettingsObject = Schema<"models.SettingsObject">

// Setting field paths used by FE. Mirrors the SettingName constants in
// go/models/settings.go — keeping them as a literal-union here gives
// us compile-time autocomplete on patch() calls without re-deriving
// the path strings at every call site.
export const SETTING_NOTIFICATIONS_WARRANTY_EXPIRY = "notifications.warranty_expiry"
export const SETTING_NOTIFICATIONS_MAINTENANCE_REMINDER = "notifications.maintenance_reminder"
export const SETTING_NOTIFICATIONS_WEEKLY_DIGEST = "notifications.weekly_digest"
export const SETTING_NOTIFICATIONS_PRICE_DROP = "notifications.price_drop"
export const SETTING_NOTIFICATIONS_LOAN_REMINDER = "notifications.loan_reminder"
export const SETTING_NOTIFICATIONS_CHANNEL_EMAIL = "notifications.channel.email"
export const SETTING_NOTIFICATIONS_CHANNEL_PUSH = "notifications.channel.push"
export const SETTING_APPEARANCE_DEFAULT_ITEMS_VIEW = "appearance.default_items_view"
export const SETTING_APPEARANCE_PREFERRED_DISPLAY_CURRENCY = "appearance.preferred_display_currency"
export const SETTING_APPEARANCE_NUMBER_FORMAT_LOCALE = "appearance.number_format_locale"
// appearance.language is the user's UI language (en/cs/ru). It is the
// cross-device source of truth for the interface language AND the language
// the backend localizes transactional emails in (#2090).
export const SETTING_APPEARANCE_LANGUAGE = "appearance.language"

export async function getSettings(signal?: AbortSignal): Promise<SettingsObject> {
  // The rewrite middleware in lib/http prepends `/g/{active-slug}` —
  // see GROUP_REWRITE_PATHS. Settings rows are user-scoped so any of
  // the user's groups produces the same payload, but the active slug
  // still parameterises the cache key in hooks.ts to be safe.
  return http.get<SettingsObject>("/settings", { signal })
}

export async function patchSetting(field: string, value: unknown): Promise<SettingsObject> {
  // JSON-encode primitives explicitly. The lib/http transport sends a
  // string body as-is (so callers can pre-stringify when needed), so a
  // bare string like "cs-CZ" would arrive on the BE as the literal text
  // "cs-CZ" — which `json.Unmarshal` rejects as not-valid-JSON and
  // bounces with a 400. Numbers and booleans already round-trip
  // correctly via http.patch's auto-stringify path, but going through
  // JSON.stringify here unconditionally keeps the wire format
  // consistent across every value type accepted by SettingsObject.
  return http.patch<SettingsObject>(`/settings/${encodeURIComponent(field)}`, JSON.stringify(value))
}
