DROP TABLE IF EXISTS exports;
DROP TABLE IF EXISTS settings;
DROP TABLE IF EXISTS manuals;
DROP TABLE IF EXISTS invoices;
DROP TABLE IF EXISTS images;
DROP TABLE IF EXISTS commodities;
DROP TABLE IF EXISTS areas;
DROP TABLE IF EXISTS locations;
