apiVersion: v1
kind: Service
metadata:
  name: {{ include "inventario.fullname" . }}
  labels:
    {{- include "inventario.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "inventario.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 3333
      protocol: TCP
