// eslint-disable-next-line @typescript-eslint/no-restricted-imports -- removed in #1331
import { library } from '@fortawesome/fontawesome-svg-core'
// eslint-disable-next-line @typescript-eslint/no-restricted-imports -- removed in #1331
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

// Import solid icons
// eslint-disable-next-line @typescript-eslint/no-restricted-imports -- removed in #1331
import {
  faBlender,
  faLaptop,
  faTools,
  faCouch,
  faTshirt,
  faBox,
  faFilePdf,
  faFileImage,
  faBook,
  faFileInvoiceDollar,
  faFile,
  faFileAlt,
  faDownload,
  faTrash,
  faTimes,
  faPencilAlt,
  faCheck,
  faPrint,
  faEdit,
  faPlus,
  faSearch,
  faEye,
  faInfoCircle,
  faArrowLeft,
  faArrowRight,
  faQuoteLeftAlt,
  faMapMarkerAlt,
  faChevronDown,
  faChevronRight,
  faChevronLeft,
  faSearchMinus,
  faSearchPlus,
  faCopy,
  faUpload,
  faCloudUploadAlt,
  faExclamationTriangle,
  faExclamationCircle,
  faCheckCircle,
  faSpinner,
  faRedo,
  faCalendar,
  faImage,
  faVideo,
  faMusic,
  faArchive,
  faSave,
  faExternalLinkAlt,
  faFileExport,
  faLock,
  faBan,
  faUser,
  faUserPlus,
  faRightFromBracket,
  faChevronUp
} from '@fortawesome/free-solid-svg-icons'

// Add icons to the library
library.add(
  // Commodity types
  faBlender,
  faLaptop,
  faTools,
  faCouch,
  faTshirt,
  faBox,

  // File types
  faFilePdf,
  faFileImage,
  faBook,
  faFileInvoiceDollar,
  faFile,
  faFileAlt,

  // Actions
  faDownload,
  faTrash,
  faTimes,
  faPencilAlt,
  faCheck,
  faPrint,
  faEdit,
  faPlus,
  faSearch,
  faEye,
  faInfoCircle,
  faArrowLeft,
  faArrowRight,
  faQuoteLeftAlt,
  faMapMarkerAlt,
  faChevronDown,
  faChevronRight,
  faChevronLeft,
  faSearchMinus,
  faSearchPlus,
  faCopy,
  faUpload,
  faCloudUploadAlt,
  faExclamationTriangle,
  faExclamationCircle,
  faCheckCircle,
  faSpinner,
  faRedo,
  faCalendar,
  faImage,
  faVideo,
  faMusic,
  faArchive,
  faSave,
  faExternalLinkAlt,
  faFileExport,
  faLock,
  faBan,
  faUser,
  faUserPlus,
  faRightFromBracket,
  faChevronUp
)

export { FontAwesomeIcon }
