{{- if .Values.demo.minio.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inventario.demoMinioSecretName" . }}
  labels:
    {{- include "inventario.labels" . | nindent 4 }}
    app.kubernetes.io/component: demo-minio
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ .Values.demo.minio.rootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.demo.minio.rootPassword | quote }}
  MINIO_BUCKET_NAME: {{ .Values.demo.minio.bucket | quote }}
{{- end }}
