name: Swagger Docs Sync

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  swagger-docs:
    name: Check Swagger Docs Sync
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v5

      - id: vars
        uses: ./.github/actions/vars

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ steps.vars.outputs.go_version }}
          cache: true

      - name: Install dependencies
        run: go mod download
        working-directory: go

      - name: Install swag CLI
        run: |
          go install github.com/swaggo/swag/cmd/swag@${{ steps.vars.outputs.swag_version }}
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Regenerate Swagger docs
        run: swag init --output docs
        working-directory: go

      - name: Check for uncommitted changes in docs/
        run: |
          if ! git diff --exit-code -- docs/; then
            echo "Swagger docs are out of sync. Please run 'swag init --output docs' and commit the changes." >&2
            exit 1
          fi
        working-directory: go
