name: Swagger Docs Sync

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  swagger-docs:
    uses: ./.github/workflows/reusable-swagger-docs.yml
    with:
      go-version: '1.24.1'
