name: Ptah Go Lint

on:
  push:
    branches:
      - master
    paths:
      - 'ptah/**'
      - '.github/workflows/ptah-lint.yml'
  pull_request:
    paths:
      - 'ptah/**'
      - '.github/workflows/ptah-lint.yml'

permissions:
  contents: read
  pull-requests: read

jobs:
  go-lint:
    name: ptah-go-lint
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'
          cache: true
          cache-dependency-path: ptah/go.sum
      
      - name: Install dependencies
        run: go mod download
        working-directory: ptah
      
      - name: Golint
        uses: golangci/golangci-lint-action@v8
        with:
          args: --timeout=30m
          version: v2.1.6
          working-directory: ptah
