# Reusable Go Lint Workflow
name: Reusable Go Lint

on:
  workflow_call:
    inputs:
      go-version:
        required: true
        type: string
      golangci-lint-version:
        required: false
        type: string
        default: v2.1.5

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          args: --timeout=30m
          version: ${{ inputs.golangci-lint-version }}
