# Reusable Go Test Workflow
name: Reusable Go Test

on:
  workflow_call:
    inputs:
      go-version:
        required: true
        type: string

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}
          cache: true
      - name: Install dependencies
        run: go mod download
      - name: Run tests
        run: go test -v ./...
